### ISSUE TITLE
Crash when loading a scene that has an instance of it self

### ISSUE THREAD

**Issue by Sajdkick** [Chainsawkitten/LargeGameProjectEngine#156]
Create a scene.
Save it.
Instantiate it in it self.
Change scene.
Try to change back.
Crash.

**Comment by ludvigarlebrink** [comment]
You should not be able to instantiate scene to self (scene 1), meaning, the current scene should not come up as an option in the editor, since this will cause an infinite loop. However, if you instantiate another scene (scene 2) and in scene 2 you instantiate scene 1 the same error, infinite loop, will occur.

**Comment by ludvigarlebrink** [comment]
This task should maybe be split into 2 task.
- Fix in editor
- Fix in scripting and/or engine
