### ISSUE TITLE
Batching research.

### ISSUE THREAD

**Issue by SwedishSock** [Chainsawkitten/LargeGameProjectEngine#571]
Research of batching.

**Comment by Ittis** [comment]
Instanced rendering will be the best way to render for the explicit problem of a singel mesh draw many times. batching for the overall game engin is still not needed, if we in the future need to optimize our render pipeline then there is many ways to do this before needing to batch the drawcalls. 
if batching will be implemented in the future we will need to figure out a way to send massive amounts of texture data to the GPU, aka texture atlas or something similar. otherwise a bucket rendering system might be good. all depends on where the problem will be

/ittis
